name: Update Project Tree
on:
  push:
    branches:
      - main
      - master
      - gh-pages

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run tree generator
        run: |
          pip install --upgrade pip
          python generate_tree.py

      - name: Push changes
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
          authorization: |
            curl --request GET \
            --url "https://api.github.com/octocat" \
            --header "Authorization: token GH_TOKEN" \
            --header "X-GitHub-Api-Version: 2022-11-28"
        run: |
          git config --global user.name 'carloshmarques'
          git config --global user.email 'carlos.manuel.horta.marques@hotmail.com'         
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/carloshmarques/PostStrokeCodingHero.git
          git add README.md
          git commit -m "Auto-update project tree"
          git diff --quiet || git commit -m "Auto-update project tree"
          git push
        continue-on-error: true
