name: Update Project Tree

on:
  push:
    branches:
      - main
      - master
      - gh-pages

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run tree generator
        run: |
          pip install --upgrade pip
          python generate_tree.py

      - name: Commit changes
        run: |
          git config --global user.name 'carloshmmarques'
          git config --global user.email 'carlos.manuel.horta.marques@hotmail.com'
          git add README.md
          git commit -m "Auto-update project tree"
          git push
        continue-on-error: true
